//@version=5
indicator("PENGO v.1.0.1", overlay=true)

// Parameters
pengoSize = input.int(2, title="Minimum Size (Ticks)", minval=1)
showPengo = input.bool(true, title="Show Zones")
pengoEntries = input.bool(true, title="Highlight Potential Entries")

// Helpers
tickSize = syminfo.mintick

// Variables
var float aHigh = na
var float aLow = na
var float bHigh = na
var float bLow = na
var float cHigh = na
var float cLow = na
var borderPengo = 2
var borderBullish = color.new(#FFFFFF, 0)
var borderBearish = color.new(#FFFFFF, 0)
var bckgrndBullish = color.new(#FFFFFF, 90)
var bckgrndBearish = color.new(#FFFFFF, 90)

// Condition
if bar_index >= 2
    aHigh := high[2]
    aLow := low[2]
    bHigh := high[1]
    bLow := low[1]
    cHigh := high
    cLow := low

    // Check if the gap condition is met
    bullishGap = (aLow > cHigh) and (aLow - cHigh) >= pengoSize * tickSize
    bearishGap = (aHigh < cLow) and (cLow - aHigh) >= pengoSize * tickSize

    // Mark gap zones if found
    if showPengo and (bullishGap or bearishGap)
        if bullishGap
            // Bullish gap zone
            box.new(left=bar_index[2], top=cHigh, right=bar_index[0], bottom=aLow, border_color=borderBullish, bgcolor=bckgrndBullish, border_width=borderPengo)

        if bearishGap
            // Bearish gap zone
            box.new(left=bar_index[2], top=aHigh, right=bar_index[0], bottom=cLow, border_color=borderBearish, bgcolor=bckgrndBearish, border_width=borderPengo)

    // Check if the price enters the gap zone (potential entry)
    if pengoEntries
        if bullishGap and close < aLow and close > cHigh
            label.new(bar_index, close, text="Entry", style=label.style_label_down, color=color.green, textcolor=color.white, size=size.large)
        if bearishGap and close > aHigh and close < cLow
            label.new(bar_index, close, text="Entry", style=label.style_label_up, color=color.red, textcolor=color.white, size=size.large)
