// Within a timeframe specified plot a line for the highest & lowest price.

// @version=5
indicator("Corta Bear Overnight", shorttitle="cbx.overnight", overlay = true)

overNightHigh = 122 // The highest price during the overnight trading session.
overNightLow = 120 // The lowest price during the overnight trading session.

overNightHighHLine = hline( overNightHigh, title="Overnight High", color=color.green, linestyle=hline.style_solid, linewidth=1 ) // Horizontal line for overnight high
overNightLowHLine = hline( overNightLow, title="Overnight Low", color=color.red, linestyle=hline.style_solid, linewidth=1 ) // Horizontal line for overnight low

fill( overNightHighHLine, overNightLowHLine, color = color.rgb(76, 127, 181, 95) )


overnightStartHour = 0
overnightStartMinute = 0
overnightEndHour = 4
overnightEndMinute = 0

highestPrice = na

// Check if the current timestamp falls within the target time range
isOvernightSession = (hour >= overnightStartHour and minute >= overnightStartMinute) and (hour < overnightEndHour or (hour == overnightEndHour and minute <= overnightEndMinute))

// If the current timestamp is within the time range, update the highest price
if isOvernightSession
    highestPrice := na(highestPrice) ? high : math.max(high, highestPrice)

// Plot the highest price line
plot(highestPrice, title="Highest Price", color=color.blue, linewidth=2)